export default ({
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',

    GET_ROOMS: "GET_ROOMS",
    SEND_ROOMS: "SEND_ROOMS",

    ADD_NEW_ROOM: "ADD_NEW_ROOM",
    NEW_ROOM_ADDED: "NEW_ROOM_ADDED",

    SELECT_ROOM: "SELECT_ROOM",
    SEND_ROOM_DATA: "SEND_ROOM_DATA",

    NEW_MESSAGE: "NEW_MESSAGE",
    SEND_MESSAGE: "SEND_MESSAGE",

    ADD_USER_IN_ROOM: "ADD_USER_IN_ROOM",
    NEW_USER_IN_ROOM: "NEW_USER_IN_ROOM",

    LEAVE_ROOM: "LEAVE_ROOM",

    ALL_DATA_CLEARED: "ALL_DATA_CLEARED"
})

